name: Build Backslashxx KernelSU

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x build.sh
          bash build.sh

      - name: Upload results and diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Backslashxx-SuSFS-kiev
          path: output/
          if-no-files-found: warn
